import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useRouter } from 'next/router'
import { useAccessTokenStore, userStore, useUserStore } from '@/components/store'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const accessToken = useAccessTokenStore((state: any) => state.access_token);

  useEffect(() => {
    if (!accessToken) {
      router.replace("/signin");
    }
  }, [])


  return (
    <>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/1200px-Instagram.svg.png" />
      </Head>
      <main>

      </main>
    </>
  )
}
