import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useRouter } from 'next/router'
import useUserStore, { useAccessTokenStore, userStore } from '@/components/store'
import { useEffect } from 'react'
import { useCookies } from 'react-cookie'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const [cookie, setCookie] = useCookies(["cookieToken"])
  const user = useUserStore((state) => state.user);

  const checkToken = async () => {
    if (cookie.cookieToken == null) {
      router.replace("/signin")
    }
  }

  const checkUserDataIfNotPresentFetch = async () => {
    if (user.email == "") {

    }
  }

  useEffect(() => {
    checkToken()

    checkUserDataIfNotPresentFetch();
  }, [cookie])


  return (
    <>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/1200px-Instagram.svg.png" />
      </Head>
      <main>
        <button onClick={() => console.log(user)}>Click Me</button>
      </main>
    </>
  )
}
